# Generated by Django 5.2.13 on 2026-05-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_alter_userregister_password_interviewsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='meeting_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
