# Generated by Django 4.2 on 2026-05-10 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("detection", "0003_interviewsession_meeting_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interviewsession",
            name="meeting_id",
        ),
        migrations.CreateModel(
            name="QuestionResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_id", models.IntegerField()),
                ("question", models.TextField()),
                ("category", models.CharField(max_length=50)),
                ("difficulty", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=20)),
                ("time_spent", models.IntegerField()),
                ("asked_at", models.DateTimeField(auto_now_add=True)),
                ("question_number", models.IntegerField()),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="detection.interviewsession",
                    ),
                ),
            ],
        ),
    ]
