# Generated by Django 4.2 on 2026-05-12 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("detection", "0004_remove_interviewsession_meeting_id_questionresponse"),
    ]

    operations = [
        migrations.DeleteModel(
            name="QuestionResponse",
        ),
    ]
