# Generated by Django 4.2 on 2026-05-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detection", "0005_delete_questionresponse"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userregister",
            old_name="name",
            new_name="username",
        ),
        migrations.AddField(
            model_name="userregister",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("user", "User")],
                default="user",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="userregister",
            name="password",
            field=models.CharField(max_length=100),
        ),
    ]
