# Generated by Django 4.2 on 2026-05-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "detection",
            "0006_rename_name_userregister_username_userregister_role_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewsession",
            name="attended_questions",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="avg_score",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="rejected_questions",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="success_percentage",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="total_questions",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="verdict",
            field=models.CharField(default="Normal", max_length=50),
        ),
    ]
