# Generated by Django 4.2 on 2026-05-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detection", "0007_interviewsession_attended_questions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detectionlog",
            name="behavior",
            field=models.CharField(default="Normal", max_length=100),
        ),
        migrations.AlterField(
            model_name="detectionlog",
            name="face_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="detectionlog",
            name="final_status",
            field=models.CharField(default="Normal", max_length=100),
        ),
        migrations.AlterField(
            model_name="detectionlog",
            name="lip_status",
            field=models.CharField(default="Normal", max_length=100),
        ),
        migrations.AlterField(
            model_name="detectionlog",
            name="score",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="interviewsession",
            name="verdict",
            field=models.CharField(default="Pending", max_length=50),
        ),
        migrations.AlterField(
            model_name="userregister",
            name="role",
            field=models.CharField(default="user", max_length=20),
        ),
    ]
